### ISSUE TITLE
MelCloud plugin makes Domoticz crash if database auto save is enabled

### ISSUE THREAD

**Issue by Patricen1** [gysmo38/domoticz-python-melcloud#32]
Using Domoticz troubleshooting guide [https://www.domoticz.com/wiki/Troubleshooting#Crash_log](https://www.domoticz.com/wiki/Troubleshooting#Crash_log) I finally figured out that plugin makes Domoticz crash hourly.

Does anybody experience the same issue, and how could it be solved?

Thread 8 (Thread 0x690f6200 (LWP 22760)):
#0  __waitpid (options=0, stat_loc=0x690f4f98, pid=24403) at ../sysdeps/unix/sys                                                                                                                                                             v/linux/waitpid.c:30
#1  __waitpid (pid=24403, stat_loc=0x690f4f98, options=0) at ../sysdeps/unix/sys                                                                                                                                                             v/linux/waitpid.c:25
#2  0x0029121c in dumpstack_gdb(bool) ()
#3  0x002917e8 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  <signal handler called>
#7  0x75d3d724 in ?? () from /usr/lib/arm-linux-gnueabihf/libpython3.7m.so
#8  0x75d3d714 in ?? () from /usr/lib/arm-linux-gnueabihf/libpython3.7m.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by Patricen1** [comment]
Hello,

I finally managed to get rid of this issue that was related to a lot of garbage that was the source of domoticz.db file growing up to 400MB.

To do this, I had to remove one of the devices (unit fan status) that had millions of events logged .

My issue is now how to restore the deleted item?
I tried enabling new devices and refreshing Melcloud plug-in hardware, but the device does not show up.

Any idea about that?

Thanks
