### ISSUE TITLE
Loads of errors with plugin 

### ISSUE THREAD

**Issue by MikeyMan83** [gysmo38/domoticz-python-melcloud#7]
Hi all,

Have been running melcloud for a while now, without any issues. However, since a while, it seems to hang my whole domoticz setup. Looking at the logs, there's a lot of errors returning:
`2020-10-02 13:56:42.171  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:42.171  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:42.359  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:42.462  Error: (Mitsubishi Airco) 'onMessage' failed 'KeyError'.
2020-10-02 13:56:42.462  Error: (Mitsubishi Airco) ----> Line 450 in '/home/pi/domoticz/plugins/MELCloud/plugin.py', function onMessage
2020-10-02 13:56:42.462  Error: (Mitsubishi Airco) ----> Line 145 in '/home/pi/domoticz/plugins/MELCloud/plugin.py', function onMessage
2020-10-02 13:56:42.462  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:42.463  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:42.645  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:42.697  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:42.697  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:42.932  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:42.984  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:42.985  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:43.161  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:43.213  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:43.213  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:43.395  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:43.446  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:43.447  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:43.680  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:43.732  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:43.733  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:43.973  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:44.025  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:44.025  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:44.261  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:44.313  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:44.313  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:44.547  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:44.604  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:44.604  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:44.797  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:44.849  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:44.849  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:45.038  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:45.089  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:45.090  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:45.277  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:45.329  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:45.329  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:45.522  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:45.574  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:45.574  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:45.776  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:45.833  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:45.834  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:46.077  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:46.129  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:46.129  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:46.311  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:46.363  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:46.363  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:46.607  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:46.659  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:46.659  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:46.945  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:46.997  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:46.997  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:47.258  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:47.310  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:47.310  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:47.553  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:47.605  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:47.606  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:47.845  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:47.897  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:47.897  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:48.334  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:48.386  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:48.386  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:48.630  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:48.682  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:48.682  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:48.863  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:48.915  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:48.915  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:49.099  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:49.151  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:49.151  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:49.385  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:49.438  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:49.438  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:49.669  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:49.726  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:49.726  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:49.970  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:50.021  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:50.172  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:50.492  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:50.543  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:50.595  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:50.833  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:50.935  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:50.936  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:51.178  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:51.230  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:51.230  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:51.467  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:51.518  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:51.519  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:51.760  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:51.810  (Mitsubishi Airco) MELCloud receive unknonw message with error code 404
2020-10-02 13:56:51.861  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.074  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.315  (Mitsubishi Airco) MELCloud connection FAIL: Operation already in progress
2020-10-02 13:56:52.316  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:52.316  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.316  Error: (Mitsubishi Airco) No transport, write directive to 'MELCloud' ignored.
2020-10-02 13:56:52.399  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.489  (Mitsubishi Airco) MELCloud connection FAIL: Operation canceled
2020-10-02 13:56:52.490  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.593  (Mitsubishi Airco) MELCloud connection FAIL: Operation canceled
2020-10-02 13:56:52.593  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.694  (Mitsubishi Airco) MELCloud connection FAIL: Operation canceled
2020-10-02 13:56:52.695  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.779  (Mitsubishi Airco) MELCloud connection FAIL: Operation canceled
2020-10-02 13:56:52.780  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:52.869  (Mitsubishi Airco) MELCloud connection FAIL: Operation canceled
2020-10-02 13:56:52.869  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:53.060  (Mitsubishi Airco) MELCloud connection FAIL: Operation already in progress
2020-10-02 13:56:53.061  (Mitsubishi Airco) MELCloud connection OK
2020-10-02 13:56:53.061  Error: Domoticz(pid:14342, tid:14371('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)
2020-10-02 13:56:53.061  Error: siginfo address=0x3806, address=(nil)
2020-10-02 13:56:53.061  (Mitsubishi Airco) MELCloud has disconnected
2020-10-02 13:56:53.062  Error: (Mitsubishi Airco) No transport, write directive to 'MELCloud' ignored.
2020-10-02 13:56:53.182  (Slimme Meter) P1 Smart Meter (Stroom)
2020-10-02 13:56:53.183  (Slimme Meter) General/Voltage (Voltage L1)
2020-10-02 13:56:53.188  (Slimme Meter) General/Voltage (Voltage L2)
2020-10-02 13:56:53.190  (Slimme Meter) General/Voltage (Voltage L3)
2020-10-02 13:56:53.194  (Slimme Meter) Usage (Usage L1)
2020-10-02 13:56:53.198  (Slimme Meter) Usage (Usage L2)
2020-10-02 13:56:53.203  (Slimme Meter) Usage (Usage L3)
2020-10-02 13:56:53.207  (Slimme Meter) Usage (Delivery L1)
2020-10-02 13:56:53.211  (Slimme Meter) Usage (Delivery L2)
2020-10-02 13:56:53.215  (Slimme Meter) Usage (Delivery L3)
2020-10-02 13:56:57.620  Error: Thread 22 (Thread 0x6a9f9220 (LWP 14371)):
2020-10-02 13:56:57.620  Error: #0  __waitpid (options=0, stat_loc=0x6a9f7dc8, pid=28350) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-10-02 13:56:57.620  Error: #1  __waitpid (pid=28350, stat_loc=0x6a9f7dc8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-10-02 13:56:57.620  Error: #2  0x002dbcdc in dumpstack_gdb(bool) ()
2020-10-02 13:56:57.620  Error: #3  0x002dc2a8 in signal_handler(int, siginfo_t*, void*) ()
2020-10-02 13:56:57.620  Error: #4  <signal handler called>
2020-10-02 13:56:57.621  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-10-02 13:56:57.621  Error: #6  <signal handler called>
2020-10-02 13:56:57.621  Error: #7  0x6ee290d0 in ?? ()
2020-10-02 13:56:57.621  Error: #8  0x76ca3d50 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
`

Any idea how to fix this?

**Comment by akyrio** [comment]
Hi

I've got the same issue since a couple of weeks.
Everything worked fine since 2 years, and now domoticz crash every 2 days.

2020-09-30 07:34:06.317  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:06.317  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:06.425  (melcloud2) MELCloud connection OK
2020-09-30 07:34:06.476  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:06.476  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:06.584  (melcloud2) MELCloud connection OK
2020-09-30 07:34:06.635  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:06.635  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:06.743  (melcloud2) MELCloud connection OK
2020-09-30 07:34:06.794  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:06.795  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:06.902  (melcloud2) MELCloud connection OK
2020-09-30 07:34:06.953  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:06.953  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.061  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.096  (openZwave) Current (Unknown)
2020-09-30 07:34:07.112  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.112  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.221  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.272  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.272  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.379  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.431  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.431  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.538  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.590  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.590  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.697  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.748  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.748  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:07.856  (melcloud2) MELCloud connection OK
2020-09-30 07:34:07.907  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:07.907  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.015  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.066  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.066  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.173  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.224  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.225  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.332  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.383  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.383  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.491  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.542  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.542  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.650  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.701  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.701  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.809  (melcloud2) MELCloud connection OK
2020-09-30 07:34:08.860  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:08.860  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:08.969  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.020  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.020  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.127  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.178  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.178  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.285  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.336  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.337  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.444  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.495  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.496  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.603  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.654  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.654  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.750  (openZwave) General/kWh (SECHE kWh Meter)
2020-09-30 07:34:09.762  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.813  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.813  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:09.920  (melcloud2) MELCloud connection OK
2020-09-30 07:34:09.972  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:09.972  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:10.079  (melcloud2) MELCloud connection OK
2020-09-30 07:34:10.130  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:10.130  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:10.238  (melcloud2) MELCloud connection OK
2020-09-30 07:34:10.289  (melcloud2) MELCloud receive unknonw message with error code 404
2020-09-30 07:34:10.289  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:10.396  (melcloud2) MELCloud connection OK
2020-09-30 07:34:10.397  Error: (melcloud2) No transport, write directive to 'MELCloud' ignored.
2020-09-30 07:34:10.397  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:10.481  (melcloud2) MELCloud connection OK
2020-09-30 07:34:10.482  (melcloud2) MELCloud has disconnected
2020-09-30 07:34:10.482  Error: (melcloud2) No transport, write directive to 'MELCloud' ignored.
2020-09-30 07:34:10.751  (openZwave) Usage (Unknown)
2020-09-30 07:34:10.755  (openZwave) General/kWh (SECHE kWh Meter)
2020-09-30 07:34:50.902  Error: melcloud2 hardware (23) thread seems to have ended unexpectedly
2020-10-02 01:45:00.254  Status: Domoticz V2020.2 (build 12338) (c)2012-2020 GizMoCuz
2020-10-02 01:45:00.281  Status: Build Hash: c8b66860b-modified, Date: 2020-09-06 18:27:59

**Comment by Gozzima** [comment]
Hi,

Same issue for me.
I used the MELCloud plugin for months and it was cool to control my AC from the same domoticz interface on my smartphone rather than the proprietary Mitsubishi app.
Suddenly 2 months ago, my domoticz server installed on synology NAS began to crash lets say every 2 days.
I use the last version of the MELCloud plugin : 0.7.6
I tried to upgrade domoticz, downgrade and finally tested to deactivate the MEL Cloud plugin and I see no more crashes.
Here is an extract of the last lines of my domoticz log before crash :

```
2020-09-22 17:12:36.790  Error: (Climatisation): Async Secure Read Exception: 335544539, short read
2020-09-22 17:12:36.812  (Climatisation) MELCloud receive unknonw message with error code 404
2020-09-22 17:12:36.813  (Climatisation) MELCloud has disconnected
2020-09-22 17:12:37.062  (Climatisation) MELCloud connection OK
2020-09-22 17:12:37.082  Error: (Climatisation) No transport, write directive to 'MELCloud' ignored.
2020-09-22 17:12:37.082  (Climatisation) MELCloud has disconnected
Fatal Python error: Segmentation fault

Thread 0x2cdea440 (most recent call first):
2020-09-22 17:12:37.236  Error: Domoticz(pid:10049, tid:10635('Plugin_ASIO')) received fatal signal 11 (Segmentation fault)
2020-09-22 17:12:37.239  Error: siginfo address=0x2741, address=0x2ae91e70
2020-09-22 17:12:37.458  Error: Failed to start gdb, will use backtrace() for printing stack frame

2020-09-22 17:12:37.509  Error: #0  /usr/local/domoticz/bin/domoticz() [0x15f574]
2020-09-22 17:12:37.509  Error: #1  /usr/local/domoticz/bin/domoticz() [0x16004c]
2020-09-22 17:12:37.509  Error: #2  /lib/libc.so.6 : __default_rt_sa_restorer + 0 [0x2ae91e80]

I do not see clear proof that this is the plugin that makes my domoticz crash but it is related to Python and it crashes 200 ms after an error occurs in MELCloud.
```

Thanks in advance for any help !
/Olivier

**Comment by afer92** [comment]
https://github.com/gysmo38/domoticz-python-melcloud/pull/13
